### PR TITLE
Некоторые обходной путь

### PR DESCRIPTION
**Pull request by Lanrik**

### CODE REVIEW

**Comment by DeForce** [comment]
I don't understand commit messages. Please make them in english

**Comment by Lanrik** [comment]
Чито ти написал? Пешы па русски!

**Comment by DeForce** [comment]
On stall, will review again after #96

**Comment by DeForce** [comment]
Please rebase

**Comment by Lanrik** [comment]
Я тебя не понимаю. Пиши по русски.

**Pull request closed without merging**
